### ISSUE TITLE
关于书籍封面和用户头像的一些小问题

### ISSUE THREAD

**Issue by izumedonabe** [ying-yee/Slackers#10]
你好，我把您的这个项目部署在我的服务器上之后，测试书籍的封面可以正常显示，但是后添加的书籍封面和用户自定义头像均无法显示，点击查看后显示
Not Found
The requested URL /media/xx.png was not found on this server.
能解答一下吗，谢谢

**Comment by waters00** [comment]
你好，首先非常感谢你的issue；这个问题的原因是显示头像的代码中没有包含查询本地图片的逻辑。

我将在明天修复这个问题。

**Comment by izumedonabe** [comment]
另外我还发现一个bug，在馆数量为1的图书无法借阅

**Comment by waters00** [comment]
这两个问题我已经修复了，你看看。

**Comment by izumedonabe** [comment]
确实好了
