### ISSUE TITLE
求照片原图链接.

### ISSUE THREAD

**Issue by Stoneleee** [ying-yee/Slackers#3]
![](https://camo.githubusercontent.com/8c2ba6159ebd9b22b66bf34fd2a9d1809ba1b27f/687474703a2f2f6f707366736b30377a2e626b742e636c6f7564646e2e636f6d2f70726f66696c655f312e706e67)

这是哪里po的照片，求原图链接

**Comment by waters00** [comment]
[avatars.txt](https://github.com/matthew-23/Slackers/files/1533640/avatars.txt)
确保安装wget
```shell
wget -i avatars.txt
```

**Comment by Cherry93** [comment]
怎么进入后台管理系统啊，输入http:XXX/admin会跳转，这个是怎么回事啊，求解答啊。。。

**Comment by waters00** [comment]
@Cherry93 

http://localhost:8000/admin/

用户名：admin
密码 ：admin

**Comment by Cherry93** [comment]
为啥127.0.0.1不行啊

**Comment by waters00** [comment]
行啊为啥不行

**Comment by Cherry93** [comment]
哎呀，我昨天就是不行，不知道为啥，现在又好了，好奇怪啊== 昨天就是会返回
An error occurred on the server Please contact the system administrator.==好奇怪啊。。。。。郁闷了半天

**Comment by Cherry93** [comment]
你的数据库是怎么弄进去啊==爬下来的数据，json格式导入？

**Comment by waters00** [comment]
对啊

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video

**Comment by Cherry93** [comment]
github广告都打进来了啊
